#!/usr/bin/env python3

import sys

VERSION = "1.0"

def caesar_cipher(message, shift, mode):
    result = ""

    for char in message:
        if char.isalpha():
            start = ord('A') if char.isupper() else ord('a')
            ascii_value = ord(char)

            if mode == "e":
                new_char = chr((ascii_value - start + shift) % 26 + start)
            elif mode == "d":
                new_char = chr((ascii_value - start - shift) % 26 + start)
            else:
                print("Error: Mode must be 'e' or 'd'")
                sys.exit(1)

            result += new_char
        else:
            result += char

    return result


def show_help():
    print("CryptShift - Caesar Cipher CLI Tool")
    print("\nUsage:")
    print("  cryptshift")
    print("\nAfter running, you will be prompted to enter:")
    print("  - Message")
    print("  - Shift value")
    print("  - Mode (e/d)")
    print("\nOptions:")
    print("  --help      Show help menu")
    print("  --version   Show tool version")


# ---------------- MAIN ---------------- #

if len(sys.argv) == 2:
    if sys.argv[1] == "--help":
        show_help()
        sys.exit()
    elif sys.argv[1] == "--version":
        print("CryptShift version", VERSION)
        sys.exit()

print("=== CryptShift Activated ===")

message = input("Enter message: ")

try:
    shift = int(input("Enter shift value: "))
except ValueError:
    print("Shift must be a number.")
    sys.exit(1)

mode = input("Encrypt or Decrypt? (e/d): ")

output = caesar_cipher(message, shift, mode)
print("\nResult:", output)
